version: '3.8'

services:
  soc:
    image: python:3.9-slim
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: sleep infinity

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  thehive:
    image: strangebee/thehive:5.2.0
    environment:
      - JVM_OPTS=-Xmx1g
    ports:
      - "9000:9000"
    depends_on:
      elasticsearch:
        condition: service_healthy
